version: '3'

services:
  web:
    image: odoo:16.0
    container_name: odoo16
    volumes:
      # - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db15
    # volumes:
    #   - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

# volumes:
#  odoo-web-data:
#  odoo-db-data: